### PR TITLE
fix(client): Rename `client.updateKey` => `client.updateApiKey`

### LINKED ISSUE #423: rename client.updateKey client.updateApiKey

### PR DESCRIPTION
**Pull request by ElPicador**
Closes #423

### CODE REVIEW

File: algoliasearch-common/src/main/java/com/algolia/search/APIClient.java [hunk 1]
```diff
@@ -342,7 +342,7 @@ public CreateUpdateKey addApiKey(@Nonnull ApiKey key, @Nonnull RequestOptions re
             .setData(key));
   }
 
-  /** Deprecated: use updateApiKey */
+  /** Deprecated: use {@link #updateApiKey(String, ApiKey)} */
```
Comment (aseure) [inline algoliasearch-common/src/main/java/com/algolia/search/APIClient.java:345]: Javadoc seems cool. Is it part of Javadoc to also include the `Deprecated` note (as it's already an annotation below)?

**Review by aseure — APPROVED** [review]

**Review by julienbourdeau — APPROVED** [review]

File: algoliasearch-common/src/main/java/com/algolia/search/APIClient.java (hunk 1 above)
Comment (ElPicador) [reply algoliasearch-common/src/main/java/com/algolia/search/APIClient.java:345]: No it's only me.
