### PR TITLE
Fix facet filters

### LINKED ISSUE #505: Change facetFilters type from List<String> to List<Object>
The current implementation does not support OR operations because the type of `facetFilters` is `List<String>`, which makes it impossible to pass lists of `List<String>`.

To fix this, I'll probably need to change the type for `List<Object>`. @ElPicador Could you confirm that there's no better solution?

### PR DESCRIPTION
**Pull request by aseure**
| Q                 | A
| ----------------- | ----------
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | yes    
| Related Issue     | Fix #505 
| Need Doc update   | yes

## Describe your change

This change introduces a new `FacetFilters` class to replace the `List<String>` type of the `facetFilters` parameter used in the `Query` and in the `ConsequenceParams` (extending `Query`).

## What problem is this fixing?

Currently, because a user can only define `facetFilters` as a list of strings, filters can only be `AND`ed. To be able to `OR` filters, the `facetFilters` should accept lists of list of strings as well. This is what this change is all about. Using the new `FacetFilters` abstract class that is introduced, and its `FacetFiltersAsListOfString`/`FacetFiltersAsListOfList` concrete types, one can easily set the `facetFilters` parameter of a `Query`/`ConsequenceParams` using `List<String>` or `List<List<String>>` types. As any other multi-type object of this Java client, deserialization of object returns an `Object` that can be cast to one of the concrete classes, however, this shouldn't be used that often as the `facetFilters` parameter is only sent but never returned by the API, but anyway, it's doable.

@ElPicador As it's one of the rare times I add custom (de)serializers myself, could you tell me if there's better/more idiomatic ways to write them?

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -19,3 +19,5 @@ hs_err_pid*
 *.iml
 .DS_Store
 *.logQueryTest
+
+.factorypath
```
Comment (ElPicador) [inline .gitignore:23]: what is this?

File: algoliasearch-common/src/main/java/com/algolia/search/objects/FacetFilters.java [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+  public Object deserialize(JsonParser p, DeserializationContext ctxt)
+      throws IOException, JsonProcessingException {
+    List list = p.readValueAs(List.class);
+    if (list.isEmpty()) {
+      return new FacetFiltersAsListOfString();
+    }
+    if (list.get(0) instanceof String) {
+      return new FacetFiltersAsListOfString(list);
+    }
+    return new FacetFiltersAsListOfList(list);
```
Comment (ElPicador) [inline algoliasearch-common/src/main/java/com/algolia/search/objects/FacetFilters.java:43]: I would add a check here that it's indeed a list of list

File: algoliasearch-common/src/main/java/com/algolia/search/objects/FacetFilters.java [hunk 3]
```diff
@@ -0,0 +1,76 @@
...
+      gen.writeStartArray();
+      for (List<String> l : filters.getFilters()) {
+        gen.writeStartArray();
+        for (String f : l) {
+          gen.writeString(f);
+        }
+        gen.writeEndArray();
+      }
+      gen.writeEndArray();
+    }
```
Comment (ElPicador) [inline algoliasearch-common/src/main/java/com/algolia/search/objects/FacetFilters.java:66]: missing else or at least an exception thrown

**Review by ElPicador — COMMENTED** [review]
I think you forgot the tests :P

File: .gitignore (hunk 1 above)
Comment (aseure) [reply .gitignore:23]: Apparently, files generated by Maven upon IntelliJ importing of a new project. First time I see those as well.

File: algoliasearch-common/src/main/java/com/algolia/search/objects/FacetFilters.java (hunk 2 above)
Comment (aseure) [reply algoliasearch-common/src/main/java/com/algolia/search/objects/FacetFilters.java:43]: As the `FacetFiltersAsListOfList` is expecting a `List<List<String>>`, I supposed this would throw if `list` was not of type `List<List<String>>`, hence validating the expected behaviour. Does it look wrong to you?

Otherwise, do you want me to check that the first element is of type `List<String>` and otherwise throw a custom exception?

File: algoliasearch-common/src/main/java/com/algolia/search/objects/FacetFilters.java (hunk 3 above)
Comment (aseure) [reply algoliasearch-common/src/main/java/com/algolia/search/objects/FacetFilters.java:66]: Good catch, thank you 👍

**Comment by aseure** [comment]
@ElPicador Forgot to *commit* the tests actually. Will do.

File: algoliasearch-common/src/main/java/com/algolia/search/objects/FacetFilters.java (hunk 2 above)
Comment (ElPicador) [reply algoliasearch-common/src/main/java/com/algolia/search/objects/FacetFilters.java:43]: I would throw a meaning full exception instead on relying on what the JVM will generate

**Comment by ElPicador** [comment]
> @ElPicador Forgot to _commit_ the tests actually. Will do.

I see what you did there :suspect:

File: algoliasearch-common/src/main/java/com/algolia/search/objects/FacetFilters.java [hunk 4]
```diff
@@ -0,0 +1,81 @@
...
+
+class FacetFiltersJsonSerializer extends JsonSerializer<FacetFilters> {
+
+  @Override
+  public void serialize(FacetFilters value, JsonGenerator gen, SerializerProvider serializers)
+      throws IOException {
+    if (value instanceof FacetFiltersAsListOfString) {
+      FacetFiltersAsListOfString filters = (FacetFiltersAsListOfString) value;
+      gen.writeStartArray();
+      for (String f : filters.getFilters()) {
```
Comment (Ant-hem) [inline algoliasearch-common/src/main/java/com/algolia/search/objects/FacetFilters.java]: Maybe you could use the objectMapper.readerFor method instead of the writer to have a more simple code : 
```
            ObjectReader reader = objectMapper.readerFor(new TypeReference<FacetFiltersAsListOfString>() {
            });
            FacetFiltersAsListOfString ret = reader.readValue(node);
```
