### PR TITLE
fix(client): Add one deleteIndex method (#427)

### LINKED ISSUE #427: Implement client.deleteIndex(indexName, requestOptions)

### PR DESCRIPTION
**Pull request by aseure**
Closes #427 

Apparently, the method with `RequestOptions` wasn't missing. So here, I'm just adding the one without it, to stay consistent with other methods.

# Question
However, I have a question: I've also added the `@Nonnull` annotations on the existing `deleteIndex` method. Will it break existing implementations? It will prevent people passing `null` from compiling but this is really a useful check, it's easy to fix and it shouldn't happen in the first place. WDYT?

# Test plan
As the first method is already tested for both sync and async clients, I have added no tests.

### CODE REVIEW

File: algoliasearch-common/src/main/java/com/algolia/search/APIClient.java [hunk 1]
```diff
@@ -232,6 +232,24 @@ public Task copyIndex(
     return copyIndex(srcIndexName, dstIndexName, scopes, RequestOptions.empty);
   }
 
+  public Task deleteIndex(@Nonnull String indexName) throws AlgoliaException {
```
Comment (ElPicador) [inline algoliasearch-common/src/main/java/com/algolia/search/APIClient.java]: Could you add the javadoc for those 2 methods?

**Review by ElPicador — CHANGES_REQUESTED** [review]
The method should also be added in AsyncClient.

It's ok to add the `@Nonnull` it was only an internal method that is public now.

File: algoliasearch-common/src/main/java/com/algolia/search/APIClient.java (hunk 1 above)
Comment (aseure) [reply algoliasearch-common/src/main/java/com/algolia/search/APIClient.java]: Yes right, totally forgot. Will do.

**Comment by aseure** [comment]
@ElPicador I think we're good now. Let me know.

File: algoliasearch-common/src/main/java/com/algolia/search/APIClient.java [hunk 2]
```diff
@@ -232,6 +232,39 @@ public Task copyIndex(
     return copyIndex(srcIndexName, dstIndexName, scopes, RequestOptions.empty);
   }
 
+  /**
+   * Delete an existing index
+   *
+   * @param indexName The index name that will be deleted
+   * @return The associated task
+   * @throws AlgoliaException
```
Comment (ElPicador) [inline algoliasearch-common/src/main/java/com/algolia/search/APIClient.java]: remove if you do not put a comment

File: algoliasearch-common/src/main/java/com/algolia/search/APIClient.java [hunk 3]
```diff
@@ -232,6 +232,39 @@ public Task copyIndex(
...
+    return deleteIndex(indexName, RequestOptions.empty);
+  }
+
+  /**
+   * Delete an existing index
+   *
+   * @param indexName The index name that will be deleted
+   * @param requestOptions Options to pass to this request
+   * @return The associated task
+   * @throws AlgoliaException
```
Comment (ElPicador) [inline algoliasearch-common/src/main/java/com/algolia/search/APIClient.java]: same

File: algoliasearch-common/src/main/java/com/algolia/search/AsyncAPIClient.java [hunk 4]
```diff
@@ -648,7 +648,11 @@ public String generateSecuredApiKey(
   }
 
   /** Package protected method for the Index class */
-  CompletableFuture<AsyncTask> deleteIndex(String indexName, RequestOptions requestOptions) {
+  CompletableFuture<AsyncTask> deleteIndex(@Nonnull String indexName) {
```
Comment (ElPicador) [inline algoliasearch-common/src/main/java/com/algolia/search/AsyncAPIClient.java]: the method should be public not protected anymore, like above

**Review by ElPicador — CHANGES_REQUESTED** [review]

File: algoliasearch-common/src/main/java/com/algolia/search/AsyncAPIClient.java (hunk 4 above)
Comment (aseure) [reply algoliasearch-common/src/main/java/com/algolia/search/AsyncAPIClient.java]: Ok I wasn't sure 👍

File: algoliasearch-common/src/main/java/com/algolia/search/APIClient.java (hunk 2 above)
Comment (aseure) [reply algoliasearch-common/src/main/java/com/algolia/search/APIClient.java]: Ok I'll remove it.

**Review by ElPicador — APPROVED** [review]
